# docker-compose development override for confidentialbackend
services:
  confidentialbackend:
    command: sh -c "flask --debug run --host 0.0.0.0 --port ${PORT:-8000}"
    environment:
      # sets app.config.debug
      FLASK_DEBUG: "true"
    volumes:
    # set in .env
      - ${CONFIDENTIALBACKEND_CHECKOUT_DIR}/:/opt/app
    labels:
      # rewrite headers so flask debugger thinks it's running on localhost
      - traefik.http.routers.confidentialbackend-${COMPOSE_PROJECT_NAME}.middlewares=set-dev-host
      - traefik.http.middlewares.set-dev-host.headers.customRequestHeaders.Host=localhost
      - traefik.http.middlewares.set-dev-host.headers.customRequestHeaders.X-Forwarded-Host=localhost
