# docker-compose development override for fhirwall service
version: "3.7"
services:
  confidentialbackend:
    command: sh -c "flask --debug run --host 0.0.0.0 --port ${PORT:-8000}"
    environment:
      # sets app.config.debug
      FLASK_DEBUG: "true"
    volumes:
    # set in .env
      - "${CONFIDENTIALBACKEND_CHECKOUT_DIR}/:/opt/app"
