# docker-compose development override for fishmouth
services:
  fishmouth:
    command: sh -c "flask --debug run --host 0.0.0.0 --port $${PORT:-5000}"
    environment:
      # sets app.config.debug
      FLASK_DEBUG: "true"
    volumes:
    # set in .env
      - ${FISHMOUTH_CHECKOUT_DIR}/:/opt/app
