---
services:
  fhir-base:
    image: hapiproject/hapi:${FHIR_IMAGE_TAG:-v7.6.0}
    environment:
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect

      hapi.fhir.bulk_export_enabled: "true"
      hapi.fhir.bulk_import_enabled: "true"
      # allow direct assignment of resource IDs in any format
      hapi.fhir.client_id_strategy: ANY
      # enable all endpoints for operational data
      management.endpoints.web.exposure.include: "*"
    volumes:
      # docker image does not contain any appropriate HTTP client
      # use busybox from host as `wget`
      - /usr/bin/busybox:/usr/bin/wget:ro
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - --quiet
        - http://localhost:8080/actuator/health
      start_period: 2m
    expose:
      - 8080
    depends_on:
      db:
        condition: service_healthy
